In [ ]:
import numpy as np

In [31]:
# Exercise 1

m1 = np.arange(1, 5)
m2 = np.arange(5, 9)

M = np.concatenate([m1.reshape((1, len(m1))), m2.reshape((1, len(m2)))], axis=0)

print("Matrix")
print(M)
print()

print("a)")
print(M[0, 2])
print()

print("b)")
print(M[1,:])
print()

print("c)")
print(M[:,:2])
print()

print("d)")
print(np.concatenate((M[1,:2],M[1,3:])))
print()

Matrix
[[1 2 3 4]
 [5 6 7 8]]

a)
3

b)
[5 6 7 8]

c)
[[1 2]
 [5 6]]

d)
[5 6 8]



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])