In [ ]:
import numpy as np

In [31]:
# Exercise 1

m1 = np.arange(1, 5)
m2 = np.arange(5, 9)

M = np.concatenate([m1.reshape((1, len(m1))), m2.reshape((1, len(m2)))], axis=0)

print("Matrix")
print(M)
print()

print("a)")
print(M[0, 2])
print()

print("b)")
print(M[1,:])
print()

print("c)")
print(M[:,:2])
print()

print("d)")
print(np.concatenate((M[1,:2],M[1,3:])))
print()

Matrix
[[1 2 3 4]
 [5 6 7 8]]

a)
3

b)
[5 6 7 8]

c)
[[1 2]
 [5 6]]

d)
[5 6 8]



In [38]:
# Exercise 2

X = np.logspace(-10, -16, 4)

f1 = np.empty_like(X)
f2 = np.empty_like(X)
f3 = np.empty_like(X)

for i in range(len(X)):
    f1[i] = (np.sqrt(1 - X[i]) - 1) / X[i]
    f2[i] = 1 / (np.sqrt(1 + X[i]) + 1)
    f3[i] = 1/2 + X[i]/8 + X[i]**2/16 + 5*X[i]**3/128
